### ISSUE TITLE
Can we use snp to estimate divergence time using mcmctree?

### ISSUE THREAD

**Issue by xiekunwhy** [mariodosreis/divtime#1]
Hi,

Nowadays, snps is widely use (get from RAD-seq or resequencing...), can we use snps to estimate divergence time using mcmctree program? Why or why not?

Best,
Kun

**Comment by mariodosreis** [comment]
This is not a software issue, so it will be closed now. Please use a different means of communication in the future (e.g. PAML's forum). No further questions will be answer on this channel.

To use alignments that contain only SNPs, you need to correct the likelihood, otherwise the analysis is not valid. MCMCtree currently does not implement this likelihood correction. If you have the full RADseq fragments, then you can proceed in the normal way. However, for RADseq data, is probably better to use BPP. See my paper with Anne Yoder in PNAS dating divergences of mouse lemurs in Madagascar.
